Implement models
CycloneDX/cyclonedx-core-java pull request #169
Opened 2022-01-24 02:11 UTC by DarthHater

THE OMNIBUS!

So far:
- vulnerabilities

To go:
- The rest of the 1.4 changes

2022-01-24 10:44 UTC, madpah requested changes
All looks good @DarthHater - one minor query.

2022-01-24 10:44 UTC, madpah commented on src/main/java/org/cyclonedx/model/ReleaseNotes.java
> +    "resolves",
Missing `notes`?

2022-01-24 19:11 UTC, DarthHater commented on src/main/java/org/cyclonedx/model/ReleaseNotes.java
> +    "resolves",
In: 4b971af and THANKS!

2022-01-24 20:24 UTC, DarthHater commented on src/main/java/org/cyclonedx/model/Signature.java
> +public class Signature
In: 66d3afa

2022-01-24 20:24 UTC, DarthHater commented on src/main/java/org/cyclonedx/model/vulnerability/Vulnerability.java
> +  private String bomRef;
In: 66d3afa

2022-01-24 20:24 UTC, DarthHater commented on src/main/java/org/cyclonedx/model/vulnerability/Vulnerability.java
> +public class Vulnerability
In: 66d3afa

2022-01-24 20:26 UTC, DarthHater commented
> I wonder if we should update the example pom in the README to point to 6.0.0? Currently it says:
> 
> ```
> <dependency>
>     <groupId>org.cyclonedx</groupId>
>     <artifactId>cyclonedx-core-java</artifactId>
>     <version>5.0.4</version>
> </dependency>
> ```

In: f0402ae

2022-01-24 20:53 UTC, DarthHater commented on src/main/java/org/cyclonedx/model/Service.java
> +    public void setReleaseNotes() { this.releaseNotes = releaseNotes; }
In: fd69fa7

2022-01-27 16:41 UTC, DarthHater commented on src/main/java/org/cyclonedx/model/Evidence.java
> +    @JacksonXmlElementWrapper(localName = "copyright")
Try `    @JacksonXmlElementWrapper(useWrapping = false)`, I think that's what you are after

2022-02-02 04:13 UTC, stevespringett commented
Tested with DT 4.4 and seems to work fine. No breaking changes that I can see. DT doesn't support the entire CDX 1.4 object model so unable to test that yet. But it looks good to me thus far.

2022-02-07 13:11 UTC, mealingr commented
Should "1.4" also be added here?
https://github.com/CycloneDX/cyclonedx-core-java/blob/b5b28e813cca82796cb9d8d31cae1d13ee19687c/src/main/java/org/cyclonedx/model/Pedigree.java#L48
https://cyclonedx.org/docs/1.4/json/#components_items_pedigree_patches

and here?
https://github.com/CycloneDX/cyclonedx-core-java/blob/b5b28e813cca82796cb9d8d31cae1d13ee19687c/src/main/java/org/cyclonedx/model/Service.java#L70
https://cyclonedx.org/docs/1.4/json/#services_items_properties

2022-02-07 13:20 UTC, mealingr commented on src/main/java/org/cyclonedx/model/ExternalReference.java
> +        RELEASE_NOTES("release_notes"),
```suggestion
        @JsonProperty("release-notes")
        RELEASE_NOTES("release-notes"),
```
https://github.com/CycloneDX/specification/blob/1.4/schema/bom-1.4.xsd#L776
https://github.com/CycloneDX/specification/blob/1.4/schema/bom-1.4.schema.json#L882

2022-02-07 13:36 UTC, mealingr commented on src/main/java/org/cyclonedx/model/Signature.java
> +      P_521("P-521");
I think there might be these other two as well
```suggestion
      P_521("P-521"),
      @JsonProperty("Ed25519")
      Ed25519("Ed25519"),
      @JsonProperty("Ed448")
      Ed448("Ed448");
```
https://cyclonedx.org/docs/1.4/json/#signature_oneOf_i2_publicKey_allOf_i1_then_crv

2022-02-07 13:53 UTC, mealingr commented
I think I spotted a few unused imports like
https://github.com/CycloneDX/cyclonedx-core-java/blob/b5b28e813cca82796cb9d8d31cae1d13ee19687c/src/main/java/org/cyclonedx/model/vulnerability/Vulnerability10.java#L33
may be good to go through the changed files and check for others

2022-02-16 20:03 UTC, closed without merging